### PR TITLE
Branch Deploy Example

### PR DESCRIPTION
**Pull request by GrantBirki**
This pull request demonstrates an example using IssueOps and GitHub Actions to deploy DNS changes with octodns and [github/branch-deploy](https://github.com/github/branch-deploy)

### CODE REVIEW

**Comment by GrantBirki** [comment]
.noop

**Comment by GrantBirki** [comment]
.noop

**Comment by GrantBirki** [comment]
.deploy

**Comment by GrantBirki** [comment]
Yay the deploy worked! 🎉 

Screenshot 2024-03-09 at 10 29 56 PM

... now let's demo a force deploy to ignore things that you might get with `octodns` like too many changes at once (example)

**Comment by GrantBirki** [comment]
.deploy | FORCE=true

**Comment by GrantBirki** [comment]
No changes which is expected since the last deploy got everything up to speed. Now lets simulate something going really wrong. I will first check to see if anyone owns the deployment lock. If no one owns it (or if I do), I will start a rollback deploy to bring the `main` branch back to the production state.

**Comment by GrantBirki** [comment]
.wcid

**Comment by GrantBirki** [comment]
.deploy main

**Comment by GrantBirki** [comment]
Cool! We have rolled back. Time to unlock production and close this issue as the demo is done

**Comment by GrantBirki** [comment]
.unlock production

**Comment by ross** [comment]
Nice

**Pull request closed without merging**
